[package]
name = "ants_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6.0", features = ["dynamic"] }
rand = "0.7.3"
crossbeam = "0.8"
clap = "3.0.10"
noise = "0.7.0"